<a href="https://colab.research.google.com/github/moksliukai/python/blob/main/TarpinisPasiruosimas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **4_1-9**

Marija turi savo internetinę drabužių parduotuvę. Ji analizuoja informaciją apie nuolatinius klientus. Tam ji parašė programą. Apie klientus ji turi tokius duomenis:
•	klientų skaičius n (sveikasis skaičius 1 < n < 500);
•	klientų kodus, kodas yra marijos suteiktas aštuonženklis skaičius, kurio pirmieji keturi skaitmenys reiškia metus, tolesni du – mėnesį, kai klientas tapo nuolatiniu marijos pirkėju ir gavo nuolaidą visoms prekėms, paskutinieji du – eilės numerį;
•	dėvimų drabužių dydį (lyginiai skaičiai nuo 32 iki 56);
•	klientui taikomą nuolaidą (realusis skaičius nuo 0.0 iki 1.0).

Marija turi tekstinį failą „Duomenys.txt“ apie savo klientus, kuriame yra tokie duomenys:
•	pirmoje eilutėje – nuolatinių klientų skaičius n (sveikasis skaičius 1 < n < 500);
•	kitose n eilučių – duomenys apie klientus:
kliento kodas (natūralusis aštuonženklis skaičius);
dėvimų drabužių dydis (lyginis skaičius nuo 32 iki 56);
klientui taikoma nuolaida (realusis skaičius nuo 0.0 iki 1.0).




Marijos duomenų faile „Duomenys.txt“ įrašyta tokia informacija:
3
20230101 36 0.1
20230102 48 0.2
20230103 54 0.4

Kas bus spausdinama įvykdžius šį programos fragmentą?

In [ ]:
with open("Duomenys.txt")as f:
  n = int(f.readline())
  kodas = []
  dydis = []
  nuolaida = []
  for i in range(n):
    line = f.readline().strip().split()
    kodas.append(int(line[0]))
    dydis.append(int(line[1]))
    nuolaida.append(float(line[2]))
print(n)

for i in range(n):
  print(kodas[i], dydis[i], nuolaida[i]*100, "%")

3
20230101 36 10.0 %
20230102 48 20.0 %
20230103 54 40.0 %


Marijos klientų drabužių dydžiai įrašyti skaičių masyve dydis. Šio masyvo reikšmės yra [36, 48, 54, 52, 36, 42, 46, 38, 40, 36]. Taip pat žinmas marijos klientų skaičius n (sveikasis duomuo), kuris lygus 10.
Kas bus spausdinama, įvykdžius šį programos fragmentą?

In [ ]:
dydis = [36, 48, 54, 52, 36, 42, 46, 38, 40, 36]
kiekS = 0
kiekM = 0
kiekL = 0
for i in range(len(dydis)):
  if dydis[i] == 34 or dydis[i] == 36:
    kiekS += 1

  if dydis[i] == 38 or dydis[i] == 40:
    kiekM += 1

  if dydis[i] == 42 or dydis[i] == 44:
    kiekL += 1


print(kiekS, kiekM, kiekL)

3 2 1


Klientų nuolaidų reikšmės yra įrašytos realiųjų skaičių masyve nuolaida. Šio masyvo reikšmės yra [0.1, 0.2, 0.4, 0.2, 0.0, 0.0, 0.1, 0.2, 0.1, 0.0]. Taip pat žinomas Marijos klientų skaičius n (sveikas), kuris lygus 10.
Kuris programos fragmentas teisingai suskaičiuotų ir atspausdintų didžiausią nuolaidą?

In [ ]:
nuolaidos = [0.1, 0.2, 0.4, 0.2, 0.0, 0.0, 0.1, 0.2, 0.1, 0.0]
didNuolaida = 0

for i in range(len(nuolaidos)):
    if didNuolaida < nuolaidos[i]:
        didNuolaida = nuolaidos[i]

print("Didžiausia nuolaida:", didNuolaida)



Didžiausia nuolaida: 0.4


Marijos klientams taikomos nuolaidos įrašytos realiųjų skaičių masyve  nuolaida. Šio masyvo reikšmės yra [0.1, 0.2, 0.4, 0.2, 0.0, 0.0, 0.1, 0.2, 0.1, 0.0]. Taip pat žinomas Marijos klientų skaičius n (sveikas), kuris lygus 10. Kas bus spausdinama, įvykdžius programos fragmentą, jei kintamojo didNuolaida reikšmė yra didžiausia nuolaida?

In [ ]:
nuolaidos = [0.1, 0.2, 0.4, 0.2, 0.0, 0.0, 0.1, 0.2, 0.1, 0.0]
didNuolaida = 0.4
kiek = 0

for i in range(len(nuolaidos)):
  if didNuolaida == nuolaidos[i]:
    kiek += 1

print(kiek)

1


Marijos klientų kodai įrašyti sveikųjų skaičių masyve kodas. Šio masyvo reikšmės yra [20230101, 20230102, 20230103, 20230104, 20240105, 20240201, 20240202, 20240203, 20240204, 20240301]. Marijos klientų skaičius - 10. Kuris patikrinimas, ar klientų kodų pirmieji keturi skaitmenys yra lygūs skiačiui 2024, yra teisingas?

In [ ]:
kodas = [20230101, 20230102, 20230103, 20230104, 20240105, 20240201, 20240202, 20240203, 20240204, 20240301]
#patikrinimas = False

for i in range(len(kodas)):
    if kodas[i] // 10000 == 2024:
        #patikrinimas = True
        #break

        print("Pirmieji keturi skaitmenys lygūs 2024")


Pirmieji keturi skaitmenys lygūs 2024
Pirmieji keturi skaitmenys lygūs 2024
Pirmieji keturi skaitmenys lygūs 2024
Pirmieji keturi skaitmenys lygūs 2024
Pirmieji keturi skaitmenys lygūs 2024
Pirmieji keturi skaitmenys lygūs 2024


In [ ]:
kodas = [20230101, 20230102, 20230103, 20230104, 20240105, 20240201, 20240202, 20240203, 20240204, 20240301]


for i in range(len(kodas)):
    if kodas[i] % 10000 == 2024:
        print("Pirmieji keturi skaitmenys lygūs 2024")

In [ ]:
kodas = [20230101, 20230102, 20230103, 20230104, 20240105, 20240201, 20240202, 20240203, 20240204, 20240301]

for i in range(len(kodas)):
    if kodas[i] // 1000 % 10 == 2024:

        print("Pirmieji keturi skaitmenys lygūs 2024")

In [ ]:
kodas = [20230101, 20230102, 20230103, 20230104, 20240105, 20240201, 20240202, 20240203, 20240204, 20240301]

for i in range(len(kodas)):
    if kodas[0] == 2 and kodas[1] == 0 and kodas[2] == 2 and kodas[3] == 4:

        print("Pirmieji keturi skaitmenys lygūs 2024")

Marijos kientų kodai įrašyti sveikųjų skaičių masyve kodas. Šio masyvo reikšmės yra [20230101, 22230102, 20231303, 20230504, 20220401]. Taip pat žinomas Marijos klientų skaičius - 5. Kas bus išspausdinta, įvykdžius šį programos fragmentą?

In [ ]:
kodas =  [20230101, 22230102, 20231303, 20230504, 20220401]

for i in range(len(kodas)):
  print(kodas[i], end = "  ")
  if kodas[i] // 10000 >= 2020 and kodas[i] // 100 % 100 < 13:
    print("teisingas")
  else:
    print("neteisingas")

20230101  teisingas
22230102  teisingas
20231303  neteisingas
20230504  teisingas
20220401  teisingas


Žinomas Marijos klientų skaičius n, kuris lygus 5. jiems taikomos nuolaidos įrašytos realiųjų skaičių masyve nulaida, kurio reikšmės yra [0.1, 0.2, 0.4, 0.2, 0.2]. Kuris programos fragmentass teisingai apskaičiuotų taikomos nuolaidos vidurkį?

In [ ]:
nuolaidai =  [0.1, 0.2, 0.4, 0.2, 0.2]

suma = 0
vid = 0

for i in range(len(nuolaidai)):
  suma = suma + nuolaidai[i]
vid = suma / len(nuolaidai)
print(vid)


0.22000000000000003


Marijos klientų kodai įrašyti sveikųjų skaičių masyve kodas. Šio masyvo reikšmės yra [20230101, 20230102, 20230103, 20230124, 20240105, 20240201, 20240202, 20240203, 20240214, 20240301]. Taip pat žinomas Marijos klientų skaičius n, kuris lygus 10. Ką tikrina šis programos fragmentas?


In [ ]:
kodai = [20230101, 20230102, 20230103, 20230124, 20240105, 20240201, 20240202, 20240203, 20240214, 20240301]

for i in range(len(kodai)):
#print(kodas[i], end = "  ")
    if kodas[i] // 10000 >= 2020 and kodas[i] // 100 % 100 < 13:
        print("teisingas")
    else:
        print("neteisingas")


teisingas
teisingas
neteisingas
teisingas
teisingas


IndexError: list index out of range